// demos/persistence/react-app/src/client-entry.tsx
import { createRoot } from 'react-dom/client';
import { KeyedTodo } from './PersistedApp.jsx';

const root = document.querySelector('#root');
if (!(root instanceof HTMLElement)) throw new Error('React persistence root is missing.');

createRoot(root).render(<KeyedTodo seed={[]} onTrace={() => undefined} />);
document.documentElement.setAttribute('data-framework-activated', 'react');

// demos/persistence/solid-app/src/client-entry.tsx
/** @jsxImportSource solid-js */
import { render } from 'solid-js/web';
import { KeyedTodo } from './PersistedApp.jsx';

const root = document.querySelector('#root');
if (!(root instanceof HTMLElement)) throw new Error('Solid persistence root is missing.');

render(() => <KeyedTodo seed={[]} onTrace={() => undefined} />, root);
document.documentElement.setAttribute('data-framework-activated', 'solid');
