// probes/ir8-falsification/svelte/control/Child.svelte
<!-- CONTROL ARM. TODAY's emitted shape: plain <script>, untyped $props().
  Compare packages/frameworks/svelte/generated/S1.svelte. -->
<script>
	let { label, multiplier } = $props();
	let count = $state(1);
	const derived = $derived(`${label}:${count * multiplier}`);
</script>

<output data-value="derived">{derived}</output>

// probes/ir8-falsification/vue/control/Child.vue
<!-- CONTROL ARM. TODAY's emitted shape: no lang="ts", array-form defineProps.
  Compare packages/frameworks/vue/generated/S1.vue. -->
<script setup>
	import { computed, ref } from 'vue';
	const props = defineProps(['label', 'multiplier']);
	const count = ref(1);
	const derived = computed(() => `${props.label}:${count.value * props.multiplier}`);
</script>

<template>
	<output data-value="derived">{{ derived }}</output>
</template>
