// probes/ir8-falsification/react/Child.tsx
// HAND-WRITTEN PROBE. Not emitted, not a golden, not read by any test.
//
// This is what @frameless/react WOULD print if IR-8 supplied
// PropDestructuringEntry.type. Compare the real golden
// packages/frameworks/react/generated/S1.jsx, whose signature is
//   export function RenderOnce({ label, multiplier, visible, onTrace }) {
// with NO type annotation anywhere. The only delta below is the annotation.
import { useState } from 'react';

export function RenderOnce({
	label,
	multiplier,
}: {
	label: string;
	multiplier: number;
}) {
	const [count] = useState(1);
	const derived = `${label}:${count * multiplier}`;
	return <output data-value="derived">{derived}</output>;
}

// probes/ir8-falsification/svelte/Child.svelte
<!-- HAND-WRITTEN PROBE. Not emitted, not a golden, not read by any test.

  What @frameless/svelte WOULD print if IR-8 supplied the prop types. Compare
  the real golden packages/frameworks/svelte/generated/S1.svelte, whose script
  block is
    <script>
      let { label, multiplier, visible, onTrace } = $props();
  with NO annotation. Two deltas here, and they move together: `lang="ts"` and
  the type annotation on the $props() destructuring pattern. -->
<script lang="ts">
	let { label, multiplier }: { label: string; multiplier: number } = $props();
	let count = $state(1);
	const derived = $derived(`${label}:${count * multiplier}`);
</script>

<output data-value="derived">{derived}</output>
