// probes/ir8-falsification/react/control/Child.jsx
// CONTROL ARM. This is TODAY's emitted shape, verbatim in form: no types at all.
// Compare packages/frameworks/react/generated/S1.jsx.
import { useState } from 'react';

export function RenderOnce({ label, multiplier }) {
	const [count] = useState(1);
	return <output data-value="derived">{`${label}:${count * multiplier}`}</output>;
}

// probes/ir8-falsification/solid/control/Child.jsx
// CONTROL ARM. TODAY's emitted shape: no types at all.
// Compare packages/frameworks/solid/generated/S1.jsx.
import { createSignal } from 'solid-js';

export function RenderOnce(props) {
	const [count] = createSignal(1);
	return <output data-value="derived">{`${props.label}:${count() * props.multiplier}`}</output>;
}
