// probes/ir8-falsification/qwik/control/Child.jsx
// CONTROL ARM. TODAY's emitted shape: no types at all.
// Compare packages/frameworks/qwik/generated/S1.jsx.
import { component$, useComputed$, useSignal } from '@qwik.dev/core';

export const RenderOnce = component$((props) => {
	const count = useSignal(1);
	const derived = useComputed$(() => `${props.label}:${count.value * props.multiplier}`);
	return <output data-value="derived">{derived.value}</output>;
});

// probes/ir8-falsification/solid/control/Child.jsx
// CONTROL ARM. TODAY's emitted shape: no types at all.
// Compare packages/frameworks/solid/generated/S1.jsx.
import { createSignal } from 'solid-js';

export function RenderOnce(props) {
	const [count] = createSignal(1);
	return <output data-value="derived">{`${props.label}:${count() * props.multiplier}`}</output>;
}
