// demos/vue-official/src/App.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import AsyncBoard from './emitted/AsyncBoard.vue'
import AttrBoard from './emitted/AttrBoard.vue'
import BranchBoard from './emitted/BranchBoard.vue'
import EventForm from './emitted/EventForm.vue'
import FormBoard from './emitted/FormBoard.vue'
import KeyedTodo from './emitted/KeyedTodo.vue'
import NestedBoard from './emitted/NestedBoard.vue'
import RenderOnce from './emitted/RenderOnce.vue'
import WhitespaceBoard from './emitted/WhitespaceBoard.vue'
import {
  armS8Gate,
  noTrace,
  s8Gate,
  s8ResolvedGate,
  s2Seed,
  s4Seed,
  s5Seed,
  s6Label,
  s6Seed,
  s7Seed,
  s9Seed,
  scenarioFor,
} from './scenario-props'

// DELTA from create-vite-extra@5.0.2 template-ssr-vue-ts/src/App.vue, which
// renders a single fixed `<HelloWorld />`. One shared IR, five emitters: these
// three components are frameless-emitted and copied in by `pnpm copy-emitted`,
// and the props below are the same ones demos/react-official/src/App.jsx,
// demos/solid-official/src/App.jsx, demos/qwik/src/routes/** and
// demos/svelte-official/src/routes/** pass, so the five official demos are
// directly comparable.
const props = defineProps<{ url?: string }>()
const scenario = computed(() => scenarioFor(props.url))

/**
 * The activation marker the shared contract waits for before it clicks.
 *
 * Set imperatively, in Vue's own post-mount hook, in the ROOT component. Three
 * alternatives that would each be wrong:
 *
 * - a template attribute binding would be server-rendered, and the contract's
 *   `forbidInServedPayload` would correctly fail the served payload for carrying
 *   a string only activation can produce;
 * - `src/dev-sink.ts` runs at module scope, before hydration even starts, so a
 *   marker there would be a lie about interactivity;
 * - a statement after `app.mount()` in `entry-client.ts` would run before Vue
 *   flushes its mounted hooks — the shape frameless-svelte-v1 T002 explicitly
 *   ruled out — and a child component's `onMounted` would only prove that child
 *   mounted.
 *
 * The root component's `onMounted` is the last mount in the tree: Vue flushes
 * mounted hooks child-first, and the emitted component below is rendered as this
 * component's child. That ordering is asserted rather than assumed — S1/S2/S3
 * click as soon as the marker appears, and every server-rendered assertion
 * between the marker and the first click passes, across three scenarios, with no
 * settle delay anywhere in the lane.
 */
onMounted(() => {
  document.documentElement.setAttribute('data-frameless-activated', 'vue')
})

// The /s8 harness. A `ref` rather than a module-level mutable: the board reads
// `ready` as a prop, so the new promise has to arrive through a reactive
// update. Nothing here is emitted output — see `assertS8` in
// demos/react-official/three-way-contract.ts.
const s8Ready = ref<Promise<string>>(s8ResolvedGate)
</script>

<template>
  <RenderOnce
    v-if="scenario === 's1'"
    label="kit"
    v-bind:multiplier="2"
    v-bind:visible="true"
    v-bind:onTrace="noTrace"
  />
  <KeyedTodo v-else-if="scenario === 's2'" v-bind:seed="s2Seed" v-bind:onTrace="noTrace" />
  <EventForm v-else-if="scenario === 's3'" initial="hello" v-bind:onTrace="noTrace" />
  <NestedBoard v-else-if="scenario === 's4'" v-bind:seed="s4Seed" v-bind:onTrace="noTrace" />
  <BranchBoard v-else-if="scenario === 's5'" v-bind:seed="s5Seed" v-bind:onTrace="noTrace" />
  <WhitespaceBoard
    v-else-if="scenario === 's6'"
    v-bind:seed="s6Seed"
    v-bind:label="s6Label"
    v-bind:onTrace="noTrace"
  />
  <FormBoard v-else-if="scenario === 's7'" v-bind:seed="s7Seed" v-bind:onTrace="noTrace" />
  <template v-else-if="scenario === 's8'">
    <button type="button" data-harness="arm" v-on:click="s8Ready = armS8Gate()">arm</button>
    <button type="button" data-harness="release" v-on:click="s8Gate.release()">release</button>
    <p data-harness="gate">{{ s8Ready === s8ResolvedGate ? 'open' : 'held' }}</p>
    <AsyncBoard v-bind:ready="s8Ready" v-bind:onTrace="noTrace" />
  </template>
  <AttrBoard v-else v-bind:seed="s9Seed" v-bind:onTrace="noTrace" />
</template>

// demos/angular-official/src/app/app.ts
import { ApplicationRef, Component, PLATFORM_ID, inject } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { RouterOutlet } from '@angular/router';

/** The attribute the shared contract waits for before it clicks. */
const ACTIVATION_MARKER = 'data-frameless-activated';

/**
 * What the DOM looked like at the instant the marker was set. Read back by
 * `scenarios.box.ts`; see the class comment for why it is not decoration.
 */
const ACTIVATION_WITNESS = 'data-frameless-activated-with';

/**
 * DELTA from the `ng new --ssr` scaffold's `app.ts`, which renders a fixed
 * welcome page and holds a `title` signal. The template is now
 * `<router-outlet />` and the class sets the activation marker.
 *
 * ## Which post-activation signal, and why — MEASURED, not reasoned
 *
 * Angular 22 scaffolds are zoneless, so `afterNextRender` and
 * `ApplicationRef.isStable` are genuinely different events and the choice
 * between them cannot be argued from documentation. Both were instrumented in
 * this component at once, each stamping the time it fired and whether the routed
 * scenario existed in the DOM yet, and the lane was run:
 *
 *   page                          afterNextRender          isStable
 *   / (hydrating)                 t=51 scenario present    t=62 scenario present
 *   / with ng-state deleted       t=55 scenario ABSENT     t=62 scenario present
 *
 * The second row is the answer. When Angular cannot hydrate and has to render on
 * the client, the ROOT component's `afterNextRender` runs after the first render
 * pass — which is the pass that renders `<router-outlet>` and nothing inside it,
 * because the router's initial navigation has not resolved yet. `isStable` is
 * driven by `PendingTasks`, which the router's navigation registers, so it
 * cannot go true until the routed component has rendered. A marker on
 * `afterNextRender` would therefore be a claim about interactivity that is not
 * yet true, on exactly the page where it matters.
 *
 * Three alternatives that would each be wrong, for the record:
 *
 * - a template attribute binding would be server-rendered, and the contract's
 *   `forbidInServedPayload` would correctly fail the served payload for carrying
 *   a string only activation can produce;
 * - `src/dev-sink.ts` runs at module scope, before bootstrap even starts;
 * - a statement after `bootstrapApplication(...)` resolves is the shape
 *   frameless-svelte-v1 T002 ruled out, and here it is also strictly earlier
 *   than the router.
 *
 * ## Why the second attribute exists
 *
 * "Measured once, on one machine" is not a property a lane can rely on for the
 * rest of its life. So the ordering is not merely chosen, it is ASSERTED: the
 * marker records whether the routed scenario was in the DOM at the moment it was
 * written, and `scenarios.box.ts` requires `scenario-present` on every page it
 * visits. If a future Angular moves `isStable` earlier — or if someone swaps the
 * signal back — the lane goes red naming the ordering, instead of going green on
 * a marker that arrived too soon.
 *
 * RAISING A TIMEOUT IS NOT AN AVAILABLE REPAIR HERE and is forbidden on this
 * board. There is no timeout in this file to raise: the marker is set by an
 * Angular signal, and if that signal is wrong the fix is a stronger signal.
 */
@Component({
  selector: 'app-root',
  imports: [RouterOutlet],
  templateUrl: './app.html',
  styleUrl: './app.css',
})
export class App {
  constructor() {
    if (!isPlatformBrowser(inject(PLATFORM_ID))) return;
    const applicationRef = inject(ApplicationRef);
    const subscription = applicationRef.isStable.subscribe((stable) => {
      if (!stable) return;
      const scenario = document.querySelector('[data-scenario]');
      // The witness is written FIRST, so anything that can see the marker can
      // also see what the marker is claiming.
      document.documentElement.setAttribute(
        ACTIVATION_WITNESS,
        scenario ? 'scenario-present' : 'scenario-absent',
      );
      document.documentElement.setAttribute(ACTIVATION_MARKER, 'angular');
      subscription.unsubscribe();
    });
  }
}
