// probes/ir8-falsification/angular/positive/Parent.ts
// POSITIVE TWIN: same call site, correctly typed. This MUST go GREEN.
import { Component } from '@angular/core';
import { RenderOnce } from '../src/Child';

@Component({
	selector: 'frameless-parent',
	imports: [RenderOnce],
	template: ` <frameless-render-once label="s1" [multiplier]="3" /> `,
})
export class Parent {}

// probes/ir8-falsification/react/positive/Parent.tsx
// POSITIVE TWIN: identical to the negative arm except the prop is correctly
// typed. This MUST go GREEN, or the probe itself is broken and the negative
// arm's RED proves nothing.
import { RenderOnce } from '../Child';

export function Parent() {
	return <RenderOnce label="s1" multiplier={3} />;
}
